

#' Sensitivity to Selection Criteria -- Output Generation
#'
#' Using the tabular output generated by `ssc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_ssdqa()`
#'
#' @param process_output the output from `ssc_process`
#' @param output_function the name of the output function to be executed; this is provided in the message
#'                        printed to the console after `ssc_process` is finished running
#' @param alt_cohort_filter single site exploratory no time only -- a vector with the names of
#'                          alternate cohorts to display on the graph; this should be limited
#'                          to 3 or less to maintain good visibility on the graph
#'
#' @return a graph visualizing the differences between the alternate cohort definitions and
#'         the base cohort; see documentation for each output function for specifics
#'
#' @example inst/example-ssc_process_output.R
#'
#' @export
#'
ssc_output <- function(process_output,
                       output_function,
                       alt_cohort_filter = NULL){

  if(output_function == 'ssc_ss_exp_cs'){

    if(is.null(alt_cohort_filter)){
      cohort_opts <- process_output[[1]] %>% ungroup() %>% filter(cohort_id != 'base_cohort') %>%
        distinct(cohort_id) %>% pull()

      cohort_opts <- cohort_opts %>% paste0(collapse = ', ')

      cli::cli_abort(paste('Please select up to 2 alternate cohort definitions to include in the analysis.
                            Options are:', col_blue(cohort_opts)))

    }

    ssc_output <- ssc_ss_exp_cs(summary_output = process_output[[1]],
                                cohort_overlap = process_output[[2]],
                                alt_cohort_filter = alt_cohort_filter)

  }else if(output_function == 'ssc_ss_anom_cs'){

    ssc_output <- ssc_ss_anom_cs(process_output = process_output)

  }else if(output_function == 'ssc_ms_exp_cs'){

    if('list' %in% class(process_output)){inp <- process_output[[1]]}else{inp <- process_output}

    if(is.null(alt_cohort_filter)){
      cohort_opts <- inp %>% ungroup() %>% filter(cohort_id != 'base_cohort') %>%
        distinct(cohort_id) %>% pull()

      cohort_opts <- cohort_opts %>% paste0(collapse = ', ')

      cli::cli_abort(paste('Please select up to 2 alternate cohort definitions to include in the analysis.
                            Options are:', col_blue(cohort_opts)))

    }

    ssc_output <- ssc_ms_exp_cs(process_output = inp,
                                alt_cohort_filter = alt_cohort_filter)

  }else if(output_function == 'ssc_ms_anom_cs'){

    ssc_output <- ssc_ms_anom_cs(process_output = process_output)

  }else{cli::cli_abort('Please enter a valid output_function for this check')}


}
