

#' Sensitivity to Selection Criteria -- Output Generation
#'
#' Using the tabular output generated by `ssc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* | the output from `ssc_process`
#' @param alt_cohort_filter *string or vector* | required for exploratory output; a vector with the names of
#'                          alternate cohorts to display on the graph; this should be limited
#'                          to 3 or less to maintain good visibility on the graph
#' @param large_n *boolean* | for multi site analyses, a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites *vector* | when large_n is TRUE, a vector of site names that can optionally be compared against summary statistics
#'
#' @return a graph visualizing the differences between the alternate cohort definitions and
#'         the base cohort; see documentation for each output function for specifics
#'
#' @example inst/example-ssc_process_output.R
#'
#' @export
#'
ssc_output <- function(process_output,
                       alt_cohort_filter = NULL,
                       large_n = FALSE,
                       large_n_sites = NULL){

  # extract output function
  if('list' %in% class(process_output)){
    output_function <- process_output[[1]] %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()
  }else{
    output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()
  }

  if(output_function == 'ssc_ss_exp_cs'){

    if(is.null(alt_cohort_filter)){
      cohort_opts <- process_output[[1]] %>% ungroup() %>% filter(cohort_id != 'base_cohort') %>%
        distinct(cohort_id) %>% pull()

      cohort_opts <- cohort_opts %>% paste0(collapse = ', ')

      cli::cli_abort(paste('Please select up to 2 alternate cohort definitions to include in the analysis.
                            Options are:', col_blue(cohort_opts)))

    }

    ssc_output <- ssc_ss_exp_cs(summary_output = process_output[[1]],
                                cohort_overlap = process_output[[2]],
                                alt_cohort_filter = alt_cohort_filter)

  }else if(output_function == 'ssc_ss_anom_cs'){

    ssc_output <- ssc_ss_anom_cs(process_output = process_output)

  }else if(output_function == 'ssc_ms_exp_cs'){

    if('list' %in% class(process_output)){inp <- process_output[[1]]}else{inp <- process_output}

    if(is.null(alt_cohort_filter)){
      cohort_opts <- inp %>% ungroup() %>% filter(cohort_id != 'base_cohort') %>%
        distinct(cohort_id) %>% pull()

      cohort_opts <- cohort_opts %>% paste0(collapse = ', ')

      cli::cli_abort(paste('Please select up to 2 alternate cohort definitions to include in the analysis.
                            Options are:', col_blue(cohort_opts)))

    }

    ssc_output <- ssc_ms_exp_cs(process_output = inp,
                                alt_cohort_filter = alt_cohort_filter,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'ssc_ms_anom_cs'){

    ssc_output <- ssc_ms_anom_cs(process_output = process_output,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else{cli::cli_abort('Please enter a valid output_function for this check')}


}
