

#' Sensitivity to Selection Criteria -- Output Generation
#'
#' Using the tabular output generated by `ssc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `ssc_process`
#'
#' @param alt_cohort_filter *string or vector* || defaults to `NULL`
#'
#'   A vector with the names of alternate cohorts to display in the output.
#'   This should be limited to 2 or less to maintain good visibility on the graph.
#'   This parameter is required for the following check types:
#'   - `Single Site, Exploratory, Cross-Sectional`
#'   - `Multi-Site, Exploratory, Cross-Sectional`
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `ssc_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-ssc_process_output.R
#'
#' @export
#'
ssc_output <- function(process_output,
                       alt_cohort_filter = NULL,
                       large_n = FALSE,
                       large_n_sites = NULL){

  # extract output function
  if('list' %in% class(process_output)){
    output_function <- process_output[[1]] %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()
  }else{
    output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()
  }

  if(output_function == 'ssc_ss_exp_cs'){

    if(is.null(alt_cohort_filter)){
      cohort_opts <- process_output[[1]] %>% ungroup() %>% filter(cohort_id != 'base_cohort') %>%
        distinct(cohort_id) %>% pull()

      cohort_opts <- cohort_opts %>% paste0(collapse = ', ')

      cli::cli_abort(paste('Please select up to 2 alternate cohort definitions to include in the analysis.
                            Options are:', col_blue(cohort_opts)))

    }

    ssc_output <- ssc_ss_exp_cs(summary_output = process_output[[1]],
                                cohort_overlap = process_output[[2]],
                                alt_cohort_filter = alt_cohort_filter)

  }else if(output_function == 'ssc_ss_anom_cs'){

    ssc_output <- ssc_ss_anom_cs(process_output = process_output)

  }else if(output_function == 'ssc_ms_exp_cs'){

    if('list' %in% class(process_output)){inp <- process_output[[1]]}else{inp <- process_output}

    if(is.null(alt_cohort_filter)){
      cohort_opts <- inp %>% ungroup() %>% filter(cohort_id != 'base_cohort') %>%
        distinct(cohort_id) %>% pull()

      cohort_opts <- cohort_opts %>% paste0(collapse = ', ')

      cli::cli_abort(paste('Please select up to 2 alternate cohort definitions to include in the analysis.
                            Options are:', col_blue(cohort_opts)))

    }

    ssc_output <- ssc_ms_exp_cs(process_output = inp,
                                alt_cohort_filter = alt_cohort_filter,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'ssc_ms_anom_cs'){

    ssc_output <- ssc_ms_anom_cs(process_output = process_output,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else{cli::cli_abort('Please enter a valid output_function for this check')}


}
